### ISSUE TITLE
`python` is not pre-installed in addition to `python3`

### ISSUE THREAD

**Issue by cognition9144** [CircleCI-Public/cimg-aws#7]
While CircleCI's official AWS Orbs [use](https://github.com/CircleCI-Public/aws-ecs-orb/blob/05ae70253fc97259300b8d8747c0e8f6cb77abc4/src/scripts/get-prev-task.sh#L33) the `python` binary, there's only a `python3` binary in the `cimg/aws` image, which makes them incompatible by default.

A solution is pre-installing [python-is-python3](https://packages.ubuntu.com/focal/python-is-python3).

**Comment by JalexChen** [comment]
all new cimgs released after november use python3 and support the python alias since they are built off ubuntu 22.04

edit: apparently i was wrong and the python alias is not supported

cc @CircleCI-Public/orb-publishers might be something to look into. jaryt already has this aliased in the [python orb](https://github.com/CircleCI-Public/python-orb/blob/94e68ac873cfd31b35dc28178090285128cf2811/src/scripts/alias-python.sh)
